name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          npm ci

      - name: Install Playwright Browsers
        run: |
          echo "Installing Playwright browsers"
          npx playwright install --with-deps
          
      - name: Install Allure Commandline
        run: |
          echo "Installing Allure command line"
          npm install -g allure-commandline --save-dev

      - name: Run Playwright tests
        run: |
          echo "Running Playwright tests"
          npm run test

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Generate Allure Report
        if: always()
        run: |
          echo "Generating Allure report"
          npm run report:allure

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results/
          retention-days: 30
